"""add_codigo_barras_to_produto

Revision ID: 06f1c56205cb
Revises: 
Create Date: 2026-04-12 22:04:10.526213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f1c56205cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('codigo_barras', sa.String(), nullable=True))
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.drop_column('produtos', 'codigo_barras')
    # ### end Alembic commands ###
