"""Criar tabela de logs de auditoria

Revision ID: 12bc781e635d
Revises: 1e6539b48e2c
Create Date: 2026-07-05 15:52:58.598000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bc781e635d'
down_revision: Union[str, Sequence[str], None] = '1e6539b48e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('operador_nome', sa.String(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_id'), 'logs_auditoria', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_auditoria_id'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
