"""auto_mod_models_20260529_005816

Revision ID: 1e6539b48e2c
Revises: 6b981c1503e3
Create Date: 2026-05-29 00:58:20.686180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6539b48e2c'
down_revision: Union[str, Sequence[str], None] = '6b981c1503e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_suporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.String(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_suporte_id'), 'mensagens_suporte', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_suporte_id'), table_name='mensagens_suporte')
    op.drop_table('mensagens_suporte')
    # ### end Alembic commands ###
