"""Adicionar token_sessao na tabela usuarios

Revision ID: 3a10f2748566
Revises: df4b0206d287
Create Date: 2026-07-19 12:02:57.025733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a10f2748566'
down_revision: Union[str, Sequence[str], None] = 'df4b0206d287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
