"""add_broadcast_and_meal_patient_id

Revision ID: 67ccf2abe74a
Revises: df2d06f291d7
Create Date: 2026-05-23 13:46:53.832623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ccf2abe74a'
down_revision: Union[str, Sequence[str], None] = 'df2d06f291d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
