"""empty message

Revision ID: 6b981c1503e3
Revises: 6e2909eba740
Create Date: 2026-05-29 00:28:06.107046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b981c1503e3'
down_revision: Union[str, Sequence[str], None] = '6e2909eba740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_cliente_id'), 'feedbacks_cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_cliente_id'), table_name='feedbacks_cliente')
    op.drop_table('feedbacks_cliente')
    # ### end Alembic commands ###
