"""add_operador_pin

Revision ID: 78b8c1a8e0b5
Revises: 06f1c56205cb
Create Date: 2026-04-13 20:27:23.293996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b8c1a8e0b5'
down_revision: Union[str, Sequence[str], None] = '06f1c56205cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operadores_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('pin', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operadores_turno_id'), 'operadores_turno', ['id'], unique=False)
    op.add_column('movimentacoes_estoque', sa.Column('operador_nome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentacoes_estoque', 'operador_nome')
    op.drop_index(op.f('ix_operadores_turno_id'), table_name='operadores_turno')
    op.drop_table('operadores_turno')
    # ### end Alembic commands ###
