"""force_add_broadcast_and_meal_patient_id_v2

Revision ID: 824851636734
Revises: 67ccf2abe74a
Create Date: 2026-05-23 14:23:29.400415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824851636734'
down_revision: Union[str, Sequence[str], None] = '67ccf2abe74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
