"""add_patients_tables

Revision ID: 89f052bf2155
Revises: a83b7c343151
Create Date: 2026-05-23 11:26:36.269042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f052bf2155'
down_revision: Union[str, Sequence[str], None] = 'a83b7c343151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_estoque', sa.Column('usuario_nome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentacoes_estoque', 'usuario_nome')
    # ### end Alembic commands ###
