"""empty message

Revision ID: 8e02cd484929
Revises: 824851636734
Create Date: 2026-05-28 21:49:39.922267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e02cd484929'
down_revision: Union[str, Sequence[str], None] = '824851636734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnpj_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('plano', sa.String(), nullable=True),
    sa.Column('dias_teste', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnpj_whitelist_cnpj'), 'cnpj_whitelist', ['cnpj'], unique=True)
    op.create_index(op.f('ix_cnpj_whitelist_id'), 'cnpj_whitelist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cnpj_whitelist_id'), table_name='cnpj_whitelist')
    op.drop_index(op.f('ix_cnpj_whitelist_cnpj'), table_name='cnpj_whitelist')
    op.drop_table('cnpj_whitelist')
    # ### end Alembic commands ###
