"""add_asaas_dados

Revision ID: a83b7c343151
Revises: 78b8c1a8e0b5
Create Date: 2026-04-14 13:10:23.925667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83b7c343151'
down_revision: Union[str, Sequence[str], None] = '78b8c1a8e0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cliente_asaas_id', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('assinatura_asaas_id', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('plano', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('limite_contas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'limite_contas')
    op.drop_column('clientes', 'plano')
    op.drop_column('clientes', 'assinatura_asaas_id')
    op.drop_column('clientes', 'cliente_asaas_id')
    # ### end Alembic commands ###
