"""add_broadcast_and_meal_patient_id

Revision ID: df2d06f291d7
Revises: 36d8a218f41c
Create Date: 2026-05-23 13:20:48.661278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2d06f291d7'
down_revision: Union[str, Sequence[str], None] = '36d8a218f41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
