"""Adicionar token_sessao em Usuario

Revision ID: df4b0206d287
Revises: 12bc781e635d
Create Date: 2026-07-05 19:21:29.420254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4b0206d287'
down_revision: Union[str, Sequence[str], None] = '12bc781e635d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('token_sessao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'token_sessao')
    # ### end Alembic commands ###
