"""empty message

Revision ID: f095265c1569
Revises: 8e02cd484929
Create Date: 2026-05-28 22:13:03.050515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f095265c1569'
down_revision: Union[str, Sequence[str], None] = '8e02cd484929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cnpj_whitelist', sa.Column('data_fim', sa.DateTime(), nullable=False))
    op.drop_column('cnpj_whitelist', 'dias_teste')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cnpj_whitelist', sa.Column('dias_teste', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cnpj_whitelist', 'data_fim')
    # ### end Alembic commands ###
